on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  buildImage:
    environment: dev
    runs-on: ubuntu-latest
    env:
        Test: 'dupa'

    steps:

      - name: test
        run: echo $Test
  
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: TimeApi2/Dockerfile
          push: true
          tags: michalwochna/test:latest